name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check it out
        uses: actions/checkout@v2
      - name: Setup .NET 6 Preview
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Install Libman
        run: dotnet tool install -g Microsoft.Web.LibraryManager.CLI
      - name: LibMan restore
        run: libman restore
        working-directory: src/Touch.Statiq
      - name: NuGet restore
        run: dotnet restore
        working-directory: src/Touch.Statiq
      - name: Build and run Statiq
        run: dotnet run --configuration Release --no-restore
        working-directory: src/Touch.Statiq
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          external_repository: TTC-Touch/ttc-touch.github.io
          personal_token: ${{ secrets.STATIQ_CI_APIKEY }}
          publish_dir: ./src/Touch.Statiq/output
